language: bash

before_script:
    - curl -fsSL https://git.io/shellspec|sh -s -- --yes
    - export PATH=$PATH:$HOME/.local/bin/
    - mkdir -pv $HOME/.bkit/etc
    - mkdir -pv $HOME/.bkit/var

script:
    - ./devtools/test_spec.sh